clock_gettime introduces a dependency on -lrt
Without this patch I hit link errors compiling clients on travis e.g.

  In function `ocaml_mtime_elapsed_ns':
  mtime_stubs.c:(.text+0x26): undefined reference to `clock_gettime'
  mtime_stubs.c:(.text+0x47): undefined reference to `clock_gettime'
  collect2: ld returned 1 exit status
  File "caml_startup", line 1:
  Error: Error during linking
  Command exited with code 2.

Signed-off-by: David Scott <dave.scott@citrix.com>